tasks:
  - command: gp preview https://cei.bio.ed.ac.uk/exRNA_Bioinformatics/
  - name: Install conda and env
    init: |
      mkdir miniconda3 wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -u -p /workspace/miniconda3
      rm miniconda.sh
      /workspace/miniconda3/bin/conda init bash
      source ~/.bashrc

      conda config --add channels bioconda
      conda config --add channels conda-forge
      conda config --set channel_priority strict

      conda create -y -n exrna fastqc cutadapt bowtie samtools multiqc seqtk bedtools

      conda activate exrna

      clear

      echo -e "\n\nPlease copy the text on the next line:\nexrna works\n\n"

