tasks:
  - name: Install conda and env
    init: |
      mkdir -p ~/miniconda3 && cd ~/miniconda3
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
      bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
      rm ~/miniconda3/miniconda.sh
      ~/miniconda3/bin/conda init bash
      source ~/.bashrc

      conda config --add channels bioconda
      conda config --add channels conda-forge
      conda config --set channel_priority strict

      conda create -y -n exrna fastqc cutadapt bowtie samtools

      conda activate exrna

      clear

      echo -r "\n\nexrna works\n\n"
workbench:
  layout:
    - { type: 'left', size: 0.4, panels: [ { type: 'explorer', pinned: true } ] }
    - { type: 'right', size: 0.6, panels: [ { type: 'terminal', pinned: true } ] }
